# SPDX-FileCopyrightText: 2022 Samir Romdhani <samir.romdhani1994@gmail.com>
#
# SPDX-License-Identifier: MIT license

name: Test NPM Library

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Install dependencies 🔧🔧
        run: |
          npm i --force
          cd projects/scllib 
          npm i --force
      - name: Test ⛳
        run: |
          cd projects/scllib 
          npm run test
      - name: Cleanup & Upload Coverage
        shell: bash
        run: |
          rm -rf .tmp
          bash <(curl -s https://codecov.io/bash) -c -K || echo "Codecov upload failed"
      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version
      - name: Sonar
        run: |
          cd projects/scllib 
          node_modules/sonar-scanner/bin/sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectVersion=${{ steps.package-node-version.outputs.version }}
